### PR TITLE
Do not catch exceptions at marshal calls when debugging

### PR DESCRIPTION
**Pull request by sergiohs84**

### CODE REVIEW

**Comment by sergiohs84** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Pull request merged**
